### PR TITLE
Remove namedValue search from backend extractor

### LINKED ISSUE #817: Bug: NamedValueExtractor sets namedValueResource.Properties.Value to null if key vault named value.
### Report

The NamedValueExtractor sets namedValueResource.Properties.Value = null if it is a keyvault named value.

In the BackendExtractor, the method DoesBackendReferenceNamedValue then might compare a null value to backendTemplateResource.properties.title (always null when looking in Azure Resource Explorer) or .description which could also be null

### Expected Behavior

Only backends configured in the targeted API should be detected when running in single API mode

### Actual Behavior

Backends from all APIs are detected as being referenced.

### Steps to Reproduce the Problem

1. Add a certificate from Key Vault to Apim
2. Create an Api with a backend that uses the Client Certificate as Authorization Credentials
3. Run the Extractor in single API mode
4. Backends from other APIs are added to the backends arm template output

### Component

Extractor

### DevOps Resource Kit Version

1.0.0

### .NET Version

6.0.401

### OS

Windows 10 Enterprise 21H1

### Configuration

Configuration:

```yaml
version: 0.0.1
apimServiceName: example-apim-name
```

### API Management Configuration

_No response_

### Logs

```shell
example
```

### Anything else?

_No response_

### Contact Details

soe@jyskefinans.dk

### PR DESCRIPTION
**Pull request by f-alizada**
Backend extractor does not needed checks for named-value references. 
Those checks are already done in NamedValues extractor which identifies relation between backend and named values 
Closes #817

### CODE REVIEW

File: src/ArmTemplates/Extractor/EntityExtractors/BackendExtractor.cs [hunk 1]
```diff
@@ -161,13 +157,9 @@ void SaveBackendApiParametersToCache()
...
         bool DoesPolicyReferenceBackend(
             string policyContent,
-            IEnumerable<NamedValueTemplateResource> namedValueResources,
             string backendName,
             BackendTemplateResource backendTemplateResource)
         {
-            // a policy is referenced by a backend with the set-backend-service policy, which will reference use the backends name or url, or through referencing a named value that applies to the backend
-            var namedValueResourcesUsedByBackend = namedValueResources.Where(resource => this.DoesBackendReferenceNamedValue(resource, backendTemplateResource));
-            
             if (backendName != null && policyContent.Contains(backendName) ||
```
Comment (DeagleGross) [inline src/ArmTemplates/Extractor/EntityExtractors/BackendExtractor.cs:163]:
```suggestion
return (!string.IsNullOrEmpty(backendName) && policyContent.Contains(backendName) ||
backendTemplateResource.Properties.Url != null && policyContent.Contains(backendTemplateResource.Properties.Url) ||
                backendTemplateResource.Properties.Title != null && policyContent.Contains(backendTemplateResource.Properties.Title) ||
                backendTemplateResource.Properties.ResourceId != null && policyContent.Contains(backendTemplateResource.Properties.ResourceId))
```

Comment (f-alizada) [reply src/ArmTemplates/Extractor/EntityExtractors/BackendExtractor.cs]: updated all checks in this code block, thanks for review!

**Review by DeagleGross — APPROVED** [review]
