### PR TITLE
Fixes after all-apis-extractor run

### LINKED ISSUE #652: [Extractor:] Tool throws System.NullReferenceException: Object reference not set to an instance of an object.
Hi There, 

When i try to extract a single api, it works as expected, but when i try the same command with all apis, it throws below error.

Run Error logs:

[00:48:00 INF] Started generation of tag template...
[00:48:00 INF] Finished generation of tag template...
[00:48:00 INF] Started generation of api-tag template...
[00:48:00 ERR] Error occured: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.GenerateTemplates(String baseFilesGenerationDirectory, String singleApiName, List`1 multipleApiNames, Template`1 apiTemplate) in C:\Users\akathiresan\Documents\Workspace\APIM Extractor\azure-api-management-devops-resource-kit-main\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 630
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.ExecuteGenerationBasedOnConfiguration() in C:\Users\akathiresan\Documents\Workspace\APIM Extractor\azure-api-management-devops-resource-kit-main\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 175
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Applications.ExtractApplicationCommand.ExecuteCommandAsync(ExtractorParameters parameters) in C:\Users\akathiresan\Documents\Workspace\APIM Extractor\azure-api-management-devops-resource-kit-main\src\ArmTemplates\Commands\Applications\ExtractApplicationCommand.cs:line 63
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.TagApiExtractor.GenerateApiTagsTemplateAsync(String singleApiName, List`1 multipleApiNames, ExtractorParameters extractorParameters) in C:\Users\akathiresan\Documents\Workspace\APIM Extractor\azure-api-management-devops-resource-kit-main\src\ArmTemplates\Extractor\EntityExtractors\TagAPIExtractor.cs:line 55   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.GenerateApiTagTemplateAsync(String singleApiName, List`1 multipleApiNames, String baseFilesGenerationDirectory) in C:\Users\akathiresan\Documents\Workspace\APIM Extractor\azure-api-management-devops-resource-kit-main\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 417
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.GenerateTemplates(String baseFilesGenerationDirectory, String singleApiName, List`1 multipleApiNames, Template`1 apiTemplate) in C:\Users\akathiresan\Documents\Workspace\APIM Extractor\azure-api-management-devops-resource-kit-main\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 630
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.ExecuteGenerationBasedOnConfiguration() in C:\Users\akathiresan\Documents\Workspace\APIM Extractor\azure-api-management-devops-resource-kit-main\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 175
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Applications.ExtractApplicationCommand.ExecuteCommandAsync(ExtractorParameters parameters) in C:\Users\akathiresan\Documents\Workspace\APIM Extractor\azure-api-management-devops-resource-kit-main\src\ArmTemplates\Commands\Applications\ExtractApplicationCommand.cs:line 63
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Program.<>c__DisplayClass0_0.<<Main>b__1>d.MoveNext() in C:\Users\akathiresan\Documents\Workspace\APIM Extractor\azure-api-management-devops-resource-kit-main\src\ArmTemplates\Program.cs:line 37
--- End of stack trace from previous location where exception was thrown ---   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Program.Main(String[] args) in C:\Users\akathiresan\Documents\Workspace\APIM Extractor\azure-api-management-devops-resource-kit-main\src\ArmTemplates\Program.cs:line 30
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Program.<Main>(String[] args)

### PR DESCRIPTION
**Pull request by DeagleGross**
- Fixed NRE occuring when running all-apis extraction (also renamed `ApiTag` to `TagApi` template to match naming with other extractors)
- Fixed InvalidOperation occuring for `api-version-set` extractor and `product-apis` extractor by replacing `SingleOrDefault` with `FirstOrDefault`
- Fixed unrefactored `LoggerExtractor` using null variable

Closes #652

### CODE REVIEW

File: src/ArmTemplates/Extractor/EntityExtractors/LoggerExtractor.cs [hunk 1]
```diff
@@ -80,7 +79,7 @@ public async Task<Template> GenerateLoggerTemplateAsync(ExtractorParameters extr
                 loggerResource.ApiVersion = GlobalConstants.ApiVersion;
                 loggerResource.Scale = null;
 
-                if (singleApiName == null)
+                if (string.IsNullOrEmpty(singleApiName))
```
Comment (DeagleGross) [inline src/ArmTemplates/Extractor/EntityExtractors/LoggerExtractor.cs:82]: fix passing `singleApiName` to **else** branch when `singleApiName = ""`.
