### PR TITLE
fix: Gateway extraction for single-api name parameter

### LINKED ISSUE #811: Bug: Extractor not creating gateways-apis template
### Report

We are using self hosted gateways. When running the extractor for a single api (tagged to run on the hosted gateway), no gatway-apis template is being created. 

We are passing in the --extractGateways=true parameter on the command line.

This seems to occur because the Name property in the instance of ApiTemplateResource gets changed by the ProcessSingleData method in ApiDataProcessor to add the ApiRevision e.g. ;rev=1

        public void ProcessSingleData(ApiTemplateResource api)
        {
            api.OriginalName = api.Name;
            var isCurrent = api.Properties.IsCurrent;
            api.Properties.IsCurrent = null;

            if (isCurrent == true && !string.IsNullOrEmpty(api.Properties.ApiRevision))
            {
                api.ApiNameWithRevision = $"{api.Name};rev={api.Properties.ApiRevision}";
                if (!api.Name.Contains($";rev={api.Properties.ApiRevision}"))
                {
                    api.Name = $"{api.Name};rev={api.Properties.ApiRevision}";
                }
            }
        }

When the following code is reached in GatewayApiExtractor.cs the api is not returned by the linq query since it's name has been changed (to add the revision) and no longer matches the singleApiName. The apis variable is then null and no template is generated:

                    **var apis = gatewayApis.Where(x => x.Name == singleApiName);**
                    if (!apis.IsNullOrEmpty())
                    {
                        var gatewayApiResources = this.GenerateGatewayApiTemplateResources(gateway.Name, apis);
                        gatewayApiTemplate.TypedResources.GatewayApis.AddRange(gatewayApiResources);
                    }

### Expected Behavior

template gateways-api template does get created

### Actual Behavior

no gateways-api template is generated

### Steps to Reproduce the Problem

Run the extractor for a single API with 

### Component

Extractor

### DevOps Resource Kit Version

1.0

### .NET Version

dotnet 6

### OS

Windows 10 Enterprise

### Configuration

_No response_

### API Management Configuration

_No response_

### Logs

```shell
example
```

### Anything else?

_No response_

### Contact Details

edward.james.carr@gmail.com

### PR DESCRIPTION
**Pull request by f-alizada**
Add additional fetch for single api for apin-name comparing during gateway extraction. 
The response is already cached so will not add additional http calls.
Closes #811

### CODE REVIEW

File: src/ArmTemplates/Common/API/Utils/ApiClientUtils.cs [hunk 1]
```diff
@@ -52,5 +60,31 @@ public ApiClientUtils(IApisClient apisClient)
 
             return apiDictionary;
         }
+
+        public async Task<ApiTemplateResource> GetsingleApi(string apiName, ExtractorParameters extractorParameters)
```
Comment (tomkerkhove) [inline src/ArmTemplates/Common/API/Utils/ApiClientUtils.cs:64]: Biggest nit ever
```suggestion
        public async Task<ApiTemplateResource> GetSingleApi(string apiName, ExtractorParameters extractorParameters)
```

File: src/ArmTemplates/Extractor/EntityExtractors/GatewayApiExtractor.cs [hunk 2]
```diff
@@ -67,10 +72,14 @@ public class GatewayApiExtractor : IGatewayApiExtractor
 
                 if (!string.IsNullOrEmpty(singleApiName))
                 {
-                    // inluding only apis with singleApiName
-                    var apis = gatewayApis.Where(x => x.Name == singleApiName);
+                    var serviceApi = await this.apiClientUtils.GetsingleApi(singleApiName, extractorParameters);
+
+                    // inluding only api with singleApiName
```
Comment (tomkerkhove) [inline src/ArmTemplates/Extractor/EntityExtractors/GatewayApiExtractor.cs:77]:
```suggestion
                    // including only api with singleApiName
```

File: src/ArmTemplates/Extractor/EntityExtractors/GatewayApiExtractor.cs [hunk 3]
```diff
@@ -67,10 +72,14 @@ public class GatewayApiExtractor : IGatewayApiExtractor
...
+                    var apis = gatewayApis.Where(x => x.Name == serviceApi.Name).ToList();
```
Comment (tomkerkhove) [inline src/ArmTemplates/Extractor/EntityExtractors/GatewayApiExtractor.cs:78]: Should we keep casing/culture in mind here and use equals?

File: src/ArmTemplates/Extractor/EntityExtractors/GatewayApiExtractor.cs [hunk 4]
```diff
@@ -108,14 +116,11 @@ List<GatewayApiTemplateResource> GenerateGatewayApiTemplateResources(string gate
                 gatewayApiTemplateResource.Name = $"[concat(parameters('{ParameterNames.ApimServiceName}'), '/{gatewayName}/{api.Name}')]";
                 gatewayApiTemplateResource.ApiVersion = GlobalConstants.ApiVersion;
                 gatewayApiTemplateResource.Scale = null;
-                gatewayApiTemplateResource.DependsOn = string.IsNullOrEmpty(dependsOn) ? Array.Empty<string>() : new[] { dependsOn };
                 gatewayApiTemplateResource.Properties = new GatewayApiProperties 
                 {
                     ProvisioningState = "created" 
                 };
 
-                dependsOn = $"[resourceId('Microsoft.ApiManagement/service/gateways/apis', parameters('{ParameterNames.ApimServiceName}'), '{gatewayName}', '{api.Name}')]";
```
Comment (tomkerkhove) [inline src/ArmTemplates/Extractor/EntityExtractors/GatewayApiExtractor.cs:117]: Shouldn't we keep this; but movei t up?

File: tests/ArmTemplates.Tests/Extractor/Scenarios/GatewayApiExtractorTests.cs [hunk 5]
```diff
@@ -76,5 +78,116 @@ public async Task GenerateGatewayApisTemplates_ProperlyLaysTheInformation()
             gatewayResources.All(x => x.Type == ResourceTypeConstants.GatewayApi).Should().BeTrue();
             gatewayResources.All(x => x.Properties is not null).Should().BeTrue();
         }
+
+        [Fact]
+        public async Task GenerateGatewayApisTemplates_ProperlyLaysTheInformation_GivenApiNameParameterIsGiven()
```
Comment (tomkerkhove) [inline tests/ArmTemplates.Tests/Extractor/Scenarios/GatewayApiExtractorTests.cs:83]: What do you mean with ProperlyLaysTheInformation?

**Review by tomkerkhove — APPROVED** [review]

File: src/ArmTemplates/Extractor/EntityExtractors/GatewayApiExtractor.cs (hunk 4 above)
Comment (f-alizada) [reply src/ArmTemplates/Extractor/EntityExtractors/GatewayApiExtractor.cs:117]: There is no need to put dependsOn for the gatewayApis resource, since it could be uploaded in parallel while template deployment

File: src/ArmTemplates/Extractor/EntityExtractors/GatewayApiExtractor.cs (hunk 3 above)
Comment (f-alizada) [reply src/ArmTemplates/Extractor/EntityExtractors/GatewayApiExtractor.cs:78]: Since the results are retrieved from the same api and processed by the same data processor after retrieving data, it should be equal. 
Thank you for raising that.

File: tests/ArmTemplates.Tests/Extractor/Scenarios/GatewayApiExtractorTests.cs (hunk 5 above)
Comment (f-alizada) [reply tests/ArmTemplates.Tests/Extractor/Scenarios/GatewayApiExtractorTests.cs]: updated the name, thank you.

**Review by tomkerkhove — APPROVED** [review]
