### PR TITLE
Fetch by version set name approach changed

### LINKED ISSUE #827: Bug: Cannot extract based on API Versionsets
### Report

Getting error when extracting using apiversionsetname parameter
Error occured: API Version Set with this name doesn't exist
Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.Exceptions.NoApiVersionSetWithSuchNameFoundException: API Version Set with this name doesn't exist

### Expected Behavior

It should extract all the apis under the given version sets

### Actual Behavior

Error occured: API Version Set with this name doesn't exist
Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.Exceptions.NoApiVersionSetWithSuchNameFoundException: API Version Set with this name doesn't exist

### Steps to Reproduce the Problem

1. Run extractor
2. Use below command
`apim-templates extract --sourceApimName apim-dev-001 --destinationApimName apim-test-001 --resourceGroup rg-dev-001 --fileFolder c:\temp\apim-01  --apiVersionSetName sample-api`

### Component

Extractor

### DevOps Resource Kit Version

1.0.0

### .NET Version

6.0

### OS

Windows, No WSL

### Configuration

Configuration:

```yaml
version: 0.0.1
apimServiceName: example-apim-name
```

### API Management Configuration

_No response_

### Logs

```shell
example
```

### Anything else?

_No response_

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by f-alizada**
Change the approach of fetching all apis under version set. 
Parameter name is versionset name, but apis were extracting based on display name of the api, which could be changed. 
Closes #827

### CODE REVIEW

File: src/ArmTemplates/Commands/Executors/ExtractorExecutor.cs [hunk 1]
```diff
@@ -1281,5 +1281,39 @@ async Task<List<string>> GetApiNamesToExtract(string singleApiName, List<string>
 
             return apiDictionary;
         }
+
+        async Task<Dictionary<string, List<string>>> GetAllAPIsDictionaryByVersionSetName(ExtractorParameters extractorParameters)
```
Comment (DeagleGross) [inline src/ArmTemplates/Commands/Executors/ExtractorExecutor.cs:1285]: maybe we can move that to apisClient? To have a possibility to use this method in other places as well.
I am thinking of removing any unneccesary methods from `ExtractorExecutor`

File: tests/ArmTemplates.Tests/Extractor/Scenarios/ApiExtractorByVersionSetNameTests.cs [hunk 2]
```diff
@@ -0,0 +1,249 @@
...
+                parametersExtractor: mockedParametersExtractor.Object,
+                apiManagementServiceExtractor: mockedApimServiceExtractor.Object
+                );
+            extractorExecutor.SetExtractorParameters(extractorParameters);
+
+            // act
+            await extractorExecutor.GenerateAPIVersionSetTemplates();
+
+            // assert
+            var directoriesCreated = Directory.GetDirectories(currentTestDirectory);
```
Comment (DeagleGross) [inline tests/ArmTemplates.Tests/Extractor/Scenarios/ApiExtractorByVersionSetNameTests.cs:242]: we definitely need to think about separate class which knows how to create directories... (but in next PRs)
And huge thanks for mocking all of the services here :)

File: src/ArmTemplates/Commands/Executors/ExtractorExecutor.cs (hunk 1 above)
Comment (f-alizada) [reply src/ArmTemplates/Commands/Executors/ExtractorExecutor.cs:1285]: I don't think apisClient is the best place for this kind of methods, I will create additional class apisClientUtilies to hold this kind of data manipulations there :) what do you think?

File: tests/ArmTemplates.Tests/Extractor/Scenarios/ApiExtractorByVersionSetNameTests.cs (hunk 2 above)
Comment (f-alizada) [reply tests/ArmTemplates.Tests/Extractor/Scenarios/ApiExtractorByVersionSetNameTests.cs:242]: Always welcome! 
May I clarify what do you mean by creating directories? to which line you are referring ? (this line is getting list of directories)

File: src/ArmTemplates/Commands/Executors/ExtractorExecutor.cs (hunk 1 above)
Comment (DeagleGross) [reply src/ArmTemplates/Commands/Executors/ExtractorExecutor.cs:1285]: ye, we can create another place.
I am just curious if we need this API in `ExtractorExecutor`

File: tests/ArmTemplates.Tests/Extractor/Scenarios/ApiExtractorByVersionSetNameTests.cs (hunk 2 above)
Comment (DeagleGross) [reply tests/ArmTemplates.Tests/Extractor/Scenarios/ApiExtractorByVersionSetNameTests.cs:242]: I am just referring to that method inside of `ExtractorExecutor` - if we would have another component, that is responsible for creating directories, we could avoid having that big amount of mocks, but we could explicitly test that component on creation of directories

Comment (f-alizada) [reply tests/ArmTemplates.Tests/Extractor/Scenarios/ApiExtractorByVersionSetNameTests.cs:242]: Oh I have created those mocks for future plans to increase coverage by tests :) 
Folders are created as a result of running full cycle of extractors

File: src/ArmTemplates/Commands/Executors/ExtractorExecutor.cs (hunk 1 above)
Comment (f-alizada) [reply src/ArmTemplates/Commands/Executors/ExtractorExecutor.cs:1285]: Not exactly, I will check this one will update PR or answer in comment thread. 
Thank you for the review!

File: tests/ArmTemplates.Tests/Extractor/Scenarios/ApiExtractorByVersionSetNameTests.cs (hunk 2 above)
Comment (DeagleGross) [reply tests/ArmTemplates.Tests/Extractor/Scenarios/ApiExtractorByVersionSetNameTests.cs:242]: Sure, I am just proposing ideas for future, if we have time.
Resolving comment since there is no suggestion for current PR

File: src/ArmTemplates/Commands/Executors/ExtractorExecutor.cs (hunk 1 above)
Comment (f-alizada) [reply src/ArmTemplates/Commands/Executors/ExtractorExecutor.cs]: Moved to different method class. Thank you for the review

**Review by DeagleGross — APPROVED** [review]
